package cliente.ec.edu.ups.ExamenFerreteriaJEE;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2021-02-05T11:10:48.993-05:00
 * Generated source version: 2.7.11
 * 
 */
@WebService(targetNamespace = "http://service.ExamenProveedor1JEE.ups.edu.ec/", name = "ClienteServiceSOAP")
@XmlSeeAlso({ObjectFactory.class})
public interface ClienteServiceSOAP {

    @WebMethod
    @RequestWrapper(localName = "buscaProducto", targetNamespace = "http://service.ExamenProveedor1JEE.ups.edu.ec/", className = "cliente.ec.edu.ups.ExamenFerreteriaJEE.BuscaProducto")
    @ResponseWrapper(localName = "buscaProductoResponse", targetNamespace = "http://service.ExamenProveedor1JEE.ups.edu.ec/", className = "cliente.ec.edu.ups.ExamenFerreteriaJEE.BuscaProductoResponse")
    @WebResult(name = "return", targetNamespace = "")
    public cliente.ec.edu.ups.ExamenFerreteriaJEE.Producto buscaProducto(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    ) throws Exception_Exception;

    @WebMethod
    @RequestWrapper(localName = "buscarProducto", targetNamespace = "http://service.ExamenProveedor1JEE.ups.edu.ec/", className = "cliente.ec.edu.ups.ExamenFerreteriaJEE.BuscarProducto")
    @ResponseWrapper(localName = "buscarProductoResponse", targetNamespace = "http://service.ExamenProveedor1JEE.ups.edu.ec/", className = "cliente.ec.edu.ups.ExamenFerreteriaJEE.BuscarProductoResponse")
    @WebResult(name = "return", targetNamespace = "")
    public cliente.ec.edu.ups.ExamenFerreteriaJEE.Producto buscarProducto(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    ) throws Exception_Exception;

    @WebMethod
    @RequestWrapper(localName = "crearProveedor", targetNamespace = "http://service.ExamenProveedor1JEE.ups.edu.ec/", className = "cliente.ec.edu.ups.ExamenFerreteriaJEE.CrearProveedor")
    @ResponseWrapper(localName = "crearProveedorResponse", targetNamespace = "http://service.ExamenProveedor1JEE.ups.edu.ec/", className = "cliente.ec.edu.ups.ExamenFerreteriaJEE.CrearProveedorResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String crearProveedor(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1
    ) throws Exception_Exception;

    @WebMethod
    @RequestWrapper(localName = "crearPtoducto", targetNamespace = "http://service.ExamenProveedor1JEE.ups.edu.ec/", className = "cliente.ec.edu.ups.ExamenFerreteriaJEE.CrearPtoducto")
    @ResponseWrapper(localName = "crearPtoductoResponse", targetNamespace = "http://service.ExamenProveedor1JEE.ups.edu.ec/", className = "cliente.ec.edu.ups.ExamenFerreteriaJEE.CrearPtoductoResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String crearPtoducto(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1
    ) throws Exception_Exception;
}
