
package cliente.ec.edu.ups.ExamenFerreteriaJEE;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;

import ec.edu.ups.ExamenFerreteriaJEE.modelo.Producto;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2021-02-05T11:10:48.929-05:00
 * Generated source version: 2.7.11
 * 
 */

public final class ClienteServiceSOAP_ClienteServiceSOAPPort_Client {

    private static final QName SERVICE_NAME = new QName("http://service.ExamenProveedor1JEE.ups.edu.ec/", "ClienteServiceSOAPService");

    private ClienteServiceSOAP_ClienteServiceSOAPPort_Client() {
    }
    
    private Producto producto = new Producto();

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = ClienteServiceSOAPService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        ClienteServiceSOAPService ss = new ClienteServiceSOAPService(wsdlURL, SERVICE_NAME);
        ClienteServiceSOAP port = ss.getClienteServiceSOAPPort();  
        
        {
        System.out.println("Invoking buscaP...");
        java.lang.String _buscaProducto_arg0 = "Clavos 3,5";
        try {
            cliente.ec.edu.ups.ExamenFerreteriaJEE.Producto _buscaProducto__return = port.buscaProducto(_buscaProducto_arg0);
            System.out.println("buscaProducto.result=" + _buscaProducto__return.nombre);
            System.out.println("buscaProducto.result=" + _buscaProducto__return.stock);

        } catch (Exception_Exception e) { 
            System.out.println("Expected exception: Exception has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking buscarProducto...");
        java.lang.String _buscarProducto_arg0 = "";
        try {
            cliente.ec.edu.ups.ExamenFerreteriaJEE.Producto _buscarProducto__return = port.buscarProducto(_buscarProducto_arg0);
            System.out.println("buscarProducto.result=" + _buscarProducto__return);

        } catch (Exception_Exception e) { 
            System.out.println("Expected exception: Exception has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking crearProveedor...");
        java.lang.String _crearProveedor_arg0 = "";
        int _crearProveedor_arg1 = 0;
        try {
            java.lang.String _crearProveedor__return = port.crearProveedor(_crearProveedor_arg0, _crearProveedor_arg1);
            System.out.println("crearProveedor.result=" + _crearProveedor__return);

        } catch (Exception_Exception e) { 
            System.out.println("Expected exception: Exception has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking crearPtoducto...");
        java.lang.String _crearPtoducto_arg0 = "";
        int _crearPtoducto_arg1 = 0;
        try {
            java.lang.String _crearPtoducto__return = port.crearPtoducto(_crearPtoducto_arg0, _crearPtoducto_arg1);
            System.out.println("crearPtoducto.result=" + _crearPtoducto__return);

        } catch (Exception_Exception e) { 
            System.out.println("Expected exception: Exception has occurred.");
            System.out.println(e.toString());
        }
            }

        System.exit(0);
        
    }
    

	public Producto getProducto() {
		return producto;
	}

	public void setProducto(Producto producto) {
		this.producto = producto;
	}

	@Override
	public String toString() {
		return "ClienteServiceSOAP_ClienteServiceSOAPPort_Client [producto=" + producto + "]";
	}
    
    

}
