
package cliente.ec.edu.ups.ExamenFerreteriaJEE;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.11
 * 2021-02-05T11:10:48.984-05:00
 * Generated source version: 2.7.11
 */

@WebFault(name = "Exception", targetNamespace = "http://service.ExamenProveedor1JEE.ups.edu.ec/")
public class Exception_Exception extends java.lang.Exception {
    
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private cliente.ec.edu.ups.ExamenFerreteriaJEE.Exception exception;

    public Exception_Exception() {
        super();
    }
    
    public Exception_Exception(String message) {
        super(message);
    }
    
    public Exception_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public Exception_Exception(String message, cliente.ec.edu.ups.ExamenFerreteriaJEE.Exception exception) {
        super(message);
        this.exception = exception;
    }

    public Exception_Exception(String message, cliente.ec.edu.ups.ExamenFerreteriaJEE.Exception exception, Throwable cause) {
        super(message, cause);
        this.exception = exception;
    }

    public cliente.ec.edu.ups.ExamenFerreteriaJEE.Exception getFaultInfo() {
        return this.exception;
    }
}
